### ISSUE TITLE
Using `AbstractString` type in `Bcrypt.CompareHashAndPassword`.

### ISSUE THREAD

**Issue by bharatbhole** [2HgO/Bcrypt.jl#1]
There is a method defined in `Bcrypt.jl` called `CompareHashAndPassword` that takes two `String` types. Obviously this throws error when strings of variables with other string types such as `SubString` are passed to it. For example, `strip` in Julia return a `SubString` instead of a String, and when the result of `strip` is passed to `CompareHashAndPassword` it throws error. 

As suggested by Bogumił Kamiński in Julia discourse forums, this problem can be solved by using `AbstractString` instead of `String` for the argument type of `CompareHashAndPassword`. It would be great if that could be changed.

Thank you for creating this library.

**Comment by 2HgO** [comment]
hey, thanks for using this library. I should be able to get to this over the weekend. 🫡
